[project]
authors = ["Samuel M. Fischer <samufi@web.de>", "Martin Lange <martin_lange_@gmx.net>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Larecs🌲 is a performance-oriented archetype-based ECS for Mojo🔥."
name = "larecs"
platforms = ["linux-64"]
version = "0.1.1"

[tasks]

[dependencies]
max = ">=25.3,<25.4"
