[project]
authors = ["samufi <samufi@web.de>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
description = "Add a short description here"
name = "larecs"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=25.1.0.dev2025011105"
