[project]
authors = ["Samuel M. Fischer <samufi@web.de>", "Martin Lange <martin_lange_@gmx.net>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
description = "Larecs🌲 is a performance-oriented archetype-based ECS for Mojo🔥."
name = "larecs"
platforms = ["linux-64", "osx-arm64", 'linux-aarch64']
version = "0.3.0"

[tasks]

[dependencies]
max = ">=25.4,<25.5"
