[workspace]
authors = [
    "Samuel M. Fischer <samufi@web.de>",
    "Martin Lange <martin_lange_@gmx.net>",
    "Mose Schmiedel <mose@schmiednet.de>",
]
channels = ["conda-forge", "https://repo.prefix.dev/max-nightly", "https://prefix.dev/tree-d"]
description = "Larecs🌲 is a performance-oriented archetype-based ECS for Mojo🔥."
name = "larecs"
platforms = ["linux-64", "osx-arm64"]
version = "0.5.0b4"
preview = ["pixi-build"]

[tasks]
tests = { cmd = "test/run_tests.sh", default-environment = "test" }
benchmarks = { cmd = "mojo run -I src benchmark/run_benchmarks.mojo", default-environment = "default" }
update-mojo = { cmd = "python scripts/update_mojo.py", default-environment = "default" }
profiling = { cmd = "mojo run -I src -Xlinker -L\"$CONDA_PREFIX/lib\" -Xlinker -lmojotracy -DTRACY_ENABLED benchmark/run_benchmarks.mojo", default-environment = "default" }

[dependencies]
mojo = ">=1.0.0b3.dev2026071206,<2"
mojo-tracy = ">=0.2.0"

[feature.test.dependencies]
clang = ">=22.1.8,<23"
clangxx = ">=22.1.8,<23"
mogo-tester = ">=2.3.3,<3"

[feature.test.activation.env]
CC = "clang"
CXX = "clang++"

[target.linux-64.dependencies]
sysroot_linux-64 = ">=2.34,<3"

[environments]
test = ["test"] # An environment covering the "test" feature

[package]
name = {workspace = true}
version = {workspace = true}

[package.build.backend]
name = "pixi-build-rattler-build"
version = "*"
channels = ["conda-forge", "https://repo.prefix.dev/max-nightly", "https://prefix.dev/tree-d"]

[package.build.config]
recipe = "conda.recipe/recipe.yaml"
