[workspace]
authors = [
    "Samuel M. Fischer <samufi@web.de>",
    "Martin Lange <martin_lange_@gmx.net>",
    "Mose Schmiedel <mose@schmiednet.de>",
]
channels = ["conda-forge", "https://repo.prefix.dev/max-nightly"]
description = "Larecs🌲 is a performance-oriented archetype-based ECS for Mojo🔥."
name = "larecs"
platforms = ["linux-64", "osx-arm64"]
version = "0.5.0"
preview = ["pixi-build"]

[tasks]
tests = { cmd = "test/run_tests.sh", default-environment = "test" }
benchmarks = { cmd = "mojo run -I src benchmark/run_benchmarks.mojo", default-environment = "default" }

[dependencies]
mojo = ">=1.0.0b3,<1.0.0"

[feature.test.dependencies]
clang = ">=22.1.7,<23"
clangxx = ">=22.1.7,<23"

[feature.test.dependencies.mogo-tester]
git = "https://github.com/moseschmiedel/mogo_tester"
tag = "v2.3.0"

[feature.test.activation.env]
CC = "clang"
CXX = "clang++"
#clang = ">=22.1.7,<23"

[environments]
test = ["test"] # An environment covering the "test" feature

[package]
name = {workspace = true}
version = {workspace = true}

[package.build.backend]
name = "pixi-build-rattler-build"
version = "*"
channels = ["conda-forge", "https://repo.prefix.dev/max-nightly"]

[package.build.config]
recipe = "conda.recipe/recipe.yaml"
