context:
  version: "0.1.0"

package:
  name: "larecs"
  version: ${{ version }}

source:
  - git: https://github.com/samufi/larecs.git
    rev: 7a10e811eb08421bd6458f17a7dce856138bb777

build:
  number: 0
  script:
    - mojo package src/larecs -o ${{ PREFIX }}/lib/mojo/larecs.mojopkg
requirements:
  host:
    - max >= 25.2
  run:
    - ${{ pin_compatible('max') }}

tests:
  - script:
      - if: unix
        then:
          - mojo test --sanitize address -D ASSERT=all test
    requirements:
      run:
        - max >= 25.2
    files:
      recipe:
        - archetype_test.mojo
        - bitmask_test.mojo
        - component_test.mojo
        - comptime_optional_test.mojo
        - dict_test.mojo
        - entity_test.mojo
        - graph_test.mojo
        - pool_test.mojo
        - query_test.mojo
        - resource_test.mojo
        - scheduler_test.mojo
        - type_map_test.mojo
        - types_test.mojo
        - unsafe_box_test.mojo
        - world_test.mojo

about:
  homepage: https://samufi.github.io/larecs/
  license: LGPL-3.0-only
  license_file: LICENSE
  summary: A performance-oriented archetype-based ECS for Mojo🔥.
  repository: https://github.com/samufi/larecs

extra:
  maintainers:
    - samufi
    - mlange-42
  project_name: Larecs🌲
