[workspace]
authors = ["samufi <samufi@web.de>", "Martin Lange <martin_lange_@gmx.net>"]
channels = ["conda-forge", "https://repo.prefix.dev/max-nightly"]
description = "Benchmarking plots for Larecs🌲"
name = "plots"
platforms = ["linux-64", "osx-arm64"]
version = "0.4.0"

[tasks]

[dependencies]
mojo = "==1.0.0b3.dev2026062206" # BUG: last working version until https://github.com/modular/modular/issues/6719 is resolved
python = "==3.12"
matplotlib = ">=3.10.0,<4"
pandas = ">=2.2"
