[workspace]
authors = ["samufi <samufi@web.de>", "Martin Lange <martin_lange_@gmx.net>"]
channels = ["conda-forge", "https://repo.prefix.dev/max-nightly", "https://prefix.dev/tree-d"]
description = "Benchmarking plots for Larecs🌲"
name = "plots"
platforms = ["linux-64", "osx-arm64"]
version = "0.4.0"

[tasks]
plots = { cmd = "mojo run -I ../../src -Xlinker -L\"$CONDA_PREFIX/lib\" -Xlinker -lmojotracy src/aos.mojo", default-environment = "default" }

[dependencies]
mojo = ">=1.0.0b3.dev2026070806,<2"
python = "==3.12"
matplotlib = ">=3.10.0,<4"
pandas = ">=2.2"
mojo-tracy = ">=0.2.0"
