[project]
authors = ["samufi <samufi@web.de>", "Martin Lange <martin_lange_@gmx.net>"]
channels = ["conda-forge", "https://repo.prefix.dev/max-nightly"]
description = "Benchmarking plots for Larecs🌲"
name = "plots"
platforms = ["linux-64"]
version = "0.3.0"

[tasks]

[dependencies]
max = ">=25.6.0.dev2025073007,<26"
mojo = ">=25.6.0.dev2025073007,<26"
python = "==3.12"
matplotlib = ">=3.10.0,<4"
pandas = ">=2.2"
