[project]
authors = ["samufi <samufi@web.de>", "Martin Lange <martin_lange_@gmx.net>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Benchmarking plots for Larecs🌲"
name = "plots"
platforms = ["linux-64"]
version = "0.3.0"

[tasks]

[dependencies]
max = ">=25.4,<25.5"
python = "==3.12"
matplotlib = ">=3.10.0,<4"
pandas = ">=2.2"
