[project]
authors = ["samufi <samufi@web.de>", "Martin Lange <martin_lange_@gmx.net>"]
channels = ["conda-forge", "https://repo.prefix.dev/max"]
description = "Benchmarking plots for Larecs🌲"
name = "plots"
platforms = ["linux-64"]
version = "0.4.0"

[tasks]

[dependencies]
mojo = ">=25.5,<26"
python = "==3.12"
matplotlib = ">=3.10.0,<4"
pandas = ">=2.2"
