[project]
authors = ["samufi <samufi@web.de>"]
channels = ["conda-forge", "https://repo.prefix.dev/max"]
description = "Example for the usage of the larecs ECS"
name = "satellites"
platforms = ["linux-64"]
version = "0.4.0"

[tasks]

[dependencies]
mojo = "==0.25.6"
python = "==3.12"
matplotlib = ">=3.10.0,<4"
numpy = ">=1.26.4,<2"
