[project]
authors = ["samufi <samufi@web.de>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Example for the usage of the larecs ECS"
name = "satellites"
platforms = ["linux-64"]
version = "0.3.0"

[tasks]

[dependencies]
max = ">=25.4,<25.5"
python = "==3.12"
matplotlib = ">=3.10.0,<4"
numpy = ">=1.26.4,<2"
