[workspace]
authors = ["Mose Schmiedel <mose@schmiednet.de>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "scripts"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.4,<3.15"

[pypi-dependencies]
perfetto = ">=0.16.0, <0.17"
