context:
  version: ${{ env.get("LARECS_VERSION", default="0.5.0b4") | default("0.5.0b4", true) }} # the default filter is needed to map empty strings to the fallback version

package:
  name: "larecs"
  version: ${{ version }}

source:
  path: ../
  filter:
    - src/
    - scripts/
    - test/
    - pixi.toml
    - pixi.lock
    - LICENSE
    - changelog.md
    - README.md

build:
  number: 2
  script:
    - mojo precompile src/larecs -o ${{ PREFIX }}/lib/mojo/larecs.mojoc

requirements:
  build:
    - mojo-compiler >=1.0.0b3.dev2026071505, <2
    - mojo-tracy >= 0.1.0
  host:
    - mojo-compiler >=1.0.0b3.dev2026071505, <2
    - mojo-tracy >= 0.1.0
  run:
    - mojo-compiler >=1.0.0b3.dev2026071505, <2
    - mojo-tracy >= 0.1.0

tests:
  - script:
      - if: unix
        then:
          - test/run_tests.sh --no-precompile test
    requirements:
      run:
        - clang >=22.1.7, <23
        - mogo-tester >=2.3.2
        - mojo-compiler >=1.0.0b3.dev2026071505, <2
    files:
      source:
        - test/

about:
  homepage: https://samufi.github.io/larecs/
  license: LGPL-3.0-only
  license_file: LICENSE
  summary: A performance-oriented archetype-based ECS for Mojo🔥.
  repository: https://github.com/samufi/larecs

extra:
  maintainers:
    - samufi
    - mlange-42
    - moseschmiedel
  project_name: Larecs🌲
