context:
  version: "0.5.0"

package:
  name: "larecs"
  version: ${{ version }}

source:
  - git: https://github.com/samufi/larecs.git
    rev: 9b861b83434206dd9d03c9d4a6857ec96f05c2b5

build:
  number: 0
  script:
    - mojo package src/larecs -o ${{ PREFIX }}/lib/mojo/larecs.mojopkg

requirements:
  build:
    - mojo-compiler >1.0.0b1, <=1.0.0b2
  host:
    - mojo-compiler >1.0.0b1, <=1.0.0b2
  run:
    - ${{ pin_compatible('mojo-compiler') }}

tests:
  - script:
      - if: unix
        then:
          - scripts/run-tests.sh test
    requirements:
      run:
        - ${{ pin_compatible('mojo-compiler') }}
    files:
      source:
        - scripts/
        - test/
        - pixi.toml

about:
  homepage: https://samufi.github.io/larecs/
  license: LGPL-3.0-only
  license_file: LICENSE
  summary: A performance-oriented archetype-based ECS for Mojo🔥.
  repository: https://github.com/samufi/larecs

extra:
  maintainers:
    - samufi
    - mlange-42
    - moseschmiedel
  project_name: Larecs🌲
