name: Benchmarks

on: 
  push:
    branches:
    - main
  pull_request:

jobs:
  benchmarks:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install magic CLI
      run: |
        curl -ssL https://magic.modular.com | bash
        source /home/runner/.bash_profile 
 
    - name: Install mojo and dependencies
      run: |
        source /home/runner/.bash_profile 
        magic install --locked
  
    - name: Run benchmarks
      run: |
        source /home/runner/.bash_profile 
        magic run mojo -I src/ benchmark/run_benchmarks.mojo
    
    - name: Run AoS benchmarks
      run: |
        source /home/runner/.bash_profile
        cd benchmark/plots
        magic install --locked
        magic run mojo -I ../../src/ src/aos.mojo
    
    - name: Archive results
      uses: actions/upload-artifact@v4
      with:
        name: results
        path: benchmark/plots/results
