name: Test
on: 
  pull_request:
    branches:
    - main
jobs:
  test:
    name: Test job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fabasoad/setup-mojo-action@v1
      - name: Run test
        run: mojo test src/
