name: Build and test

on: 
  push:
    branches:
    - main
  pull_request:

permissions: {}

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install pixi CLI
      run: |
        curl -fsSL https://pixi.sh/install.sh | bash
        source /home/runner/.bashrc 
 
    - name: Install mojo and dependencies
      run: |
        source /home/runner/.bashrc 
        pixi install --locked
  
    - name: Run tests
      run: |
        source /home/runner/.bashrc 
        pixi run mojo test --validate-doc-strings -D ASSERT=all -I src/ test

    - name: Check formatting
      run: |
        source /home/runner/.bashrc 
        if pixi run mojo format src test benchmark 2>&1 | grep -E "reformatted|error|failed" ; then echo "Formatter failed" ; exit 1 ; else echo "Formatting OK"; fi

    - name: Run benchmarks
      run: |
        source /home/runner/.bashrc 
        pixi run mojo -I src/ benchmark/run_benchmarks.mojo

    - name: Run examples
      run: |
        source /home/runner/.bashrc
        cd examples/satellites
        pixi install --locked
        pixi run mojo -I ../../src/ model.mojo
