name: Run Unit Tests
on: 
  pull_request:
    branches:
    - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install magic CLI
      run: |
        curl -ssL https://magic.modular.com | bash
        source /home/runner/.bash_profile 
        BASHRC=$( [ -f "$HOME/.bash_profile" ] && echo "$HOME/.bash_profile" || echo "$HOME/.bashrc" )
        echo 'eval "$(magic completion --shell bash)"' >> "$BASHRC"
        source "$BASHRC"
        cat /home/runner/.bash_profile 
 
    - name: Install mojo and dependencies
      run: |
        export PATH="/home/runner/.modular/bin:$PATH"
        magic shell

    - name: Run tests
      run: |
        magic shell
        mojo test src/
