name: Run Unit Tests
on: 
  pull_request:
    branches:
    - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install magic CLI
      run: |
        curl -ssL https://magic.modular.com | bash

    - name: Install mojo and dependencies
      run: |
        magic shell

    - name: Run tests
      run: |
        mojo test src/
