name: Build and test

on: 
  push:
    branches:
    - main
  pull_request:

permissions: {}

jobs:
  build_and_test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [x64, arm64]
        exclude:
          - os: macos-latest
            arch: arm64  # macos-latest arm64 is not available on GitHub-hosted runners

    defaults:
      run:
        shell: bash -ieo pipefail {0}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install pixi CLI
      run: |
        curl -fsSL https://pixi.sh/install.sh | sh
        
    - name: Install mojo and dependencies
      run: |
        pixi install --locked
  
    - name: Run tests
      run: |
        pixi run mojo test --validate-doc-strings -D ASSERT=all -I src/ test

    - name: Check formatting
      run: |
        if pixi run mojo format src test benchmark 2>&1 | grep -E "reformatted|error|failed" ; then echo "Formatter failed" ; exit 1 ; else echo "Formatting OK"; fi

    - name: Run benchmarks
      run: |
        pixi run mojo -I src/ benchmark/run_benchmarks.mojo

    - name: Run examples
      run: |
        cd examples/satellites
        pixi install --locked
        pixi run mojo -I ../../src/ model.mojo
