name: Build and test
on: 
  push:
    branches:
    - main
  pull_request:
jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install magic CLI
      run: |
        curl -ssL https://magic.modular.com | bash
        source /home/runner/.bash_profile 
 
    - name: Install mojo and dependencies
      run: |
        source /home/runner/.bash_profile 
        magic install --locked
  
    - name: Run tests
      run: |
        source /home/runner/.bash_profile 
        magic run mojo test --validate-doc-strings --sanitize address -D ASSERT=all -I src/ test
    
    - name: Run examples
      run: |
        source /home/runner/.bash_profile
        cd examples/satellites
        magic install --locked
        magic run mojo -I ../../src/ model.mojo CI

    - name: Check formatting
      run: |
        source /home/runner/.bash_profile 
        if magic run mojo format src/* 2>&1 | grep -E "reformatted|error|failed" ; then echo "Formatter failed" ; exit 1 ; els; e echo "Formatting OK"; fi
        if magic run mojo format test/* 2>&1 | grep -E "reformatted|error|failed" ; then echo "Formatter failed" ; exit 1 ; els; e echo "Formatting OK"; fi
        if magic run mojo format benchmark/* 2>&1 | grep -E "reformatted|error|failed" ; then echo "Formatter failed" ; exit 1 ; els; e echo "Formatting OK"; fi

    - name: Run benchmarks
      run: |
        source /home/runner/.bash_profile 
        magic run mojo -I src/ benchmark/run_benchmarks.mojo
