name: Build and test
on: 
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install magic CLI
      run: |
        curl -ssL https://magic.modular.com | bash
        source /home/runner/.bash_profile 
 
    - name: Install mojo and dependencies
      run: |
        source /home/runner/.bash_profile 
        magic install --locked
  
    - name: Run tests
      run: |
        source /home/runner/.bash_profile 
        magic run mojo test --validate-doc-strings --sanitize address src/

    - name: Check formatting
      run: |
        source /home/runner/.bash_profile 
        if mojo format src/*.mojo 2>&1 | grep -E "reformatted|error|failed" ; then echo "Formatter failed" ; exit 1 ; else echo "Formatting OK"; fi
