name: Publish API docs

on:
  push:
    branches:
    - main
  pull_request:

permissions:
  contents: write
  pages: write

env:
  MODO_VERSION: v0.11.12
  HUGO_VERSION: 0.148.2

jobs:

  publish:
    name: Publish API docs
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -ieo pipefail {0}

    steps:
      - name: Checkout Larecs
        uses: actions/checkout@v3
      - name: Install pixi CLI
        run: |
          curl -ssL https://pixi.sh/install.sh | bash

      # Download Modo release
      - name: Download Modo
        run: |
          mkdir modo/
          curl -sSL https://github.com/mlange-42/modo/releases/download/${{env.MODO_VERSION}}/modo-${{env.MODO_VERSION}}-linux-amd64.tar.gz | tar -xz -C modo/

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '${{env.HUGO_VERSION}}'
          extended: true

      - name: Run AoS benchmarks
        run: |
          cd benchmark/plots
          pixi install --locked
          pixi run mojo -I ../../src/ src/aos.mojo
        
      - name: Archive benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: aos-benchmark
          path: benchmark/plots/results
      
      - name: Copy benchmark results to docs
        run: |
          mkdir -p docs/src/guide/images
          cp benchmark/plots/results/aos_benchmark.svg docs/src/guide/images/
        
      - name: Run Modo # Includes 'mojo doc' and 'mojo test'
        run: |
          pixi install --locked
          ./modo/modo build --tests ""
      
      - name: Run Hugo
        run: |
          hugo -s docs/site

      - name: Archive Doc-tests
        uses: actions/upload-artifact@v4
        with:
          name: doctest
          path: docs/test
      - name: Archive Markdown artifacts
        uses: actions/upload-artifact@v4
        with:
          name: markdown
          path: docs/site/content
      - name: Archive HTML artifacts
        uses: actions/upload-artifact@v4
        with:
          name: public
          path: docs/site/public

      - name: Deploy to GitHub Pages
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: docs/site/public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
