name: Publish API docs

on:
  push:
    branches:
    - main
  pull_request:

env:
  MODO_VERSION: 9aa8642 #0.6.0
  HUGO_VERSION: 0.140.2

jobs:

  publish:
    name: Publish API docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Larecs
        uses: actions/checkout@v3
      - name: Install magic CLI
        run: |
          curl -ssL https://magic.modular.com | bash
          source /home/runner/.bash_profile
      - name: Install mojo and dependencies
        run: |
          source /home/runner/.bash_profile
          magic install --locked
        
      # Install Modo from commit hash
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.x'
      - name: Clone Modo
        run: |
          git clone https://github.com/mlange-42/modo.git
          cd modo
          git checkout ${{env.MODO_VERSION}}
      - name: Build Modo
        run: |
          cd modo
          go get .
          go build .
      
      # Install Modo from release tyg
      #- name: Download Modo
      #  run: |
      #    curl -sSL https://github.com/mlange-42/modo/releases/download/v${{env.MODO_VERSION}}/modo-v${{env.MODO_VERSION}}-linux-amd64.tar.gz | tar -xz modo/
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '${{env.HUGO_VERSION}}'
          extended: true
      
      #- name: Generate JSON docs
      #  run: |
      #    source /home/runner/.bash_profile
      #    magic run mojo doc -o docs/larecs.json src/larecs
      - name: Create Markdown
        run: |
          source /home/runner/.bash_profile
          ./modo/modo build docs/
      #- name: Run doctests
      #  run: |
      #    source /home/runner/.bash_profile
      #    magic run mojo test -I src docs/doctest
      - name: Run hugo
        run: |
          hugo -s docs

      - name: Archive Doc-tests
        uses: actions/upload-artifact@v4
        with:
          name: doctest
          path: docs/doctest
      - name: Archive Markdown artifacts
        uses: actions/upload-artifact@v4
        with:
          name: markdown
          path: docs/content
      - name: Archive HTML artifacts
        uses: actions/upload-artifact@v4
        with:
          name: public
          path: docs/public

      - name: Deploy to GitHub Pages
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: docs/public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
