name: Release

on:
  release:
    types: [created]
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  release:
    name: Build and publish package
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -ieo pipefail {0}

    steps:
      - name: Checkout Larecs
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build conda package
        uses: prefix-dev/rattler-build-action@v0.2.37
        with:
          build-args: --channel conda-forge --channel https://repo.prefix.dev/max-nightly --channel https://repo.prefix.dev/modular-community --channel https://prefix.dev/tree-d
